
/*
 * This code is auto generated by the ChipChopEngine.io Development Console 
 * You should avoid manually editing this code as it could produce unexpected results
 * If you need to make any changes to the use of ChipChop plugins in your code
 * the safest option is to use the ChipChop Dev Console to re-build this file
 */

#ifndef CHIPCHOP_DEBUG
    #define CHIPCHOP_DEBUG true
#endif
#define SERIAL_LOG if(CHIPCHOP_DEBUG)Serial

#ifndef CHIPCHOP_CONFIG_H
#define CHIPCHOP_CONFIG_H
//* modules & plugins settings *//
// PLUGINS MANAGER
#define PLUGINS_STARTED 1
#define PLUGINS_CHIPCHOP_EXISTS 2
#define PLUGINS_RUN 3
#define PLUGINS_TOTAL_EVENTS 3
#define PLUGINS_TOTAL_CALLBACKS 20


        // CHIPCHOP ENGINE
        #define CC_SOCKET_CLOSED 1
        #define CC_CONNECTED 2
        #define CC_COMMAND_RECEIVED 3
        #define CC_TOTAL_EVENTS 3
        #define CC_TOTAL_CALLBACKS 12
        #define CC_MAX_COMPONENTS 10
        //settings
        #define CC_CAN_RUN 1
        #define CC_SEND_RATE 510
        #define CC_HEARTBEAT_INTERVAL 10000
        #define CC_USE_CLOCK 1
        #define CC_DATE_FORMAT "dd MM YY - hh:mm:ss"
        // KEEP ALIVE
        #define KEEP_ALIVE_EXISTS
        #define KEEP_ALIVE_OFF 0
        #define KEEP_ALIVE_WIFI 1
        #define KEEP_ALIVE_RESTART 2
        #define KEEP_ALIVE_AUTO 3
        //events
        #define KEEP_ALIVE_RESTARTING 1
        #define KEEP_ALIVE_TOTAL_EVENTS 1
        #define KEEP_ALIVE_TOTAL_CALLBACKS 10
        //settings
        
        #define KEEP_ALIVE_MODE KEEP_ALIVE_AUTO
        #define KEEP_ALIVE_TIMEOUT 120000
        // PrefsManager
        #define PREFS_MANAGER_EXISTS
        #define PREFS_MANAGER_TOTAL_EVENTS 1
        #define PREFS_MANAGER_TOTAL_CALLBACKS 4
        //settings
        
        #define PREFS_MANAGER_AUTO_SAVE 1
        // OTA
        #define OTA_EXISTS
        //settings
        
        #define OTA_FIRMWARE_VS "1.0"
        // WIFI PORTAL
        #define WIFI_PORTAL_EXISTS
        #define WIFI_PORTAL_STARTING 1
        #define WIFI_PORTAL_CONNECTING 2
        #define WIFI_PORTAL_LOADING_CREDENTIALS 3
        #define WIFI_PORTAL_SAVING_CREDENTIALS 4
        #define WIFI_PORTAL_RECONNECTING 5
        #define WIFI_PORTAL_CLOSING 6
        #define WIFI_PORTAL_RESTARTING 7
        #define WIFI_PORTAL_CONNECTED 7
        #define WIFI_PORTAL_DISCONNECTED 8
        #define WIFI_PORTAL_ERROR 9
        //events
        #define WIFI_PORTAL_STATUS 1
        #define WIFI_PORTAL_TOTAL_EVENTS 1
        #define WIFI_PORTAL_TOTAL_CALLBACKS 4
        //settings
        
        #define WIFI_PORTAL_AP_SSID "Motor"
        #define WIFI_PORTAL_AP_PASS ""
        #define WIFI_PORTAL_START_CHIPCHOP_ON_CONNECT 1
        #define WIFI_PORTAL_CONNECT_TO "ANY_KEEP_PREFERRED"
        #define WIFI_PORTAL_RECONNECT_INTERVAL 30000
        #define WIFI_PORTAL_TIMEOUT 180000
        #define WIFI_PORTAL_AUTO_RESTART 1
        #define WIFI_PORTAL_AUTO_RECONNECT 1

#endif
